### PR TITLE
Added Support for Windows and MacOS - React Native v0.64.2

### PR DESCRIPTION
**Pull request by ghost**
**Updated React Native version dependency to be 0.64.2 to work with MacOS and Windows**
### Addition of Windows

- Added react-native-windows version 0.64.11 to the project
- Added C# (Not C++!) Windows project and ported over native queue code
- Uses Microsoft.Data.Sqlite.Core and SqlitePCLRaw.bundle_winsqlite3 Nuget Packages
- Added Windows support to example project, which required adding a package.json to the example project
- Windows returns null when there is no next job, so modified the isJobNotEmpty method to also account for this

### Addition of MacOS

- iOS Native code was able to be re-used for Mac, so simply added MacOS support in the podspec
- Added MacOS support to example project

### Changes to Example project

- Added a package.json to the Example project
- package.json expects npm pack to run on the react-native-job-queue module, and links to the .tgz (there may be a better way to do this. Switching to Yarn would allow to use the link command directly in the package.json)
- Addition of react-native-windows and react-native-macos

### Important Notes

I did not test this on Android or iOS as I do not have an easy way of doing so. Recommend someone else can do this to make sure everything works the same. I did test on Windows 10 and MacOS Catalina, and both worked as expected.

I needed these changes for a project I was working on, so figured it would be good to put in a PR in case anything is useful 😊

### CODE REVIEW

**Comment by SimonErm** [comment]
I can't run the android/iOS app because the gradle/pod builds are failing. I think migrating to reat-native-test-app and yarn would simply the whole setup. Am i allowed to push to this branch? Otherwise i would do the changes on origin and then you can do a rebase.

**Comment by SBS-FPATE-RINALDI** [comment]
@SimonErm Windows is also having some issues now. It can't find the HRMClient or the AppRegistry module. I'll do some more debugging this week to see if I can fix it and get back to you.

**Comment by SBS-FPATE-RINALDI** [comment]
Sorry still looking into this. 

The windows version is working when imported via NPM in a separate project that I'm working on, however still just having issues getting it to work in the example project in this repo. I'll also take a look at the Mac side when I can. Thank you for your patience!

**Comment by SimonErm** [comment]
@SBS-FPATE-RINALDI is the react-native-windows  version in the seperate project the same like  in the example of this repo?
> I'll also take a look at the Mac side when I can. 

Awesome, thank you :-)

**Pull request closed without merging**
